/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00274e",
        "primary-container": "#0f3d6e",
        "on-primary": "#ffffff",
        "on-primary-container": "#84a9e0",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#a5c8ff",
        "on-primary-fixed": "#001c3a",
        "on-primary-fixed-variant": "#1e4879",
        "secondary": "#1d4ed8",
        "secondary-container": "#4069f2",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#dce1ff",
        "secondary-fixed-dim": "#b7c4ff",
        "on-secondary-fixed": "#001551",
        "on-secondary-fixed-variant": "#0039b5",
        "tertiary": "#19273a",
        "tertiary-container": "#2f3d51",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#99a8bf",
        "tertiary-fixed": "#d5e3fd",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-tertiary-fixed": "#0d1c2f",
        "on-tertiary-fixed-variant": "#3a485c",
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#43474f",
        "outline": "#737780",
        "outline-variant": "#c3c6d0",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#a5c8ff",
        "surface-tint": "#396092"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-sm": "1rem",
        "space-md": "1rem",
        "margin-sm": "1rem",
        "space-xl": "2.5rem",
        "gutter-lg": "2rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-lg": "3rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "margin": "1.5rem"
      },
      fontFamily: {
        sans: ["Public Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-lg": ["Public Sans", "sans-serif"],
        "headline-sm": ["Public Sans", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-sm": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "title-lg": ["Public Sans", "sans-serif"],
        "title-md": ["Public Sans", "sans-serif"],
        "body-sm": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "display-lg-mobile": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
};
